Repository leonardssh/vscord, pull requests merged in 2022-10, with the labels that each got.

#68 Add Reason icon
  assets/icons/reasonml.png
  src/data/languages.json
Labels: enhancement

#95 feat: vscode-settings
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
Labels: enhancement

#78 Fix: c header using manifest icon
  src/data/languages.json
Labels: enhancement

#87 feat: add Bazel (Starlark) language support
  assets/icons/bazel.png
  src/data/languages.json
Labels: enhancement

#85 feat: add support for file_size tag
  package.json
  src/activity.ts
  src/config.ts
  src/constants.ts
  src/data.ts
  src/helpers/getFileSize.ts
  yarn.lock
Labels: enhancement

#98 refactor: `getApplicationId()`
  src/helpers/getApplicationId.ts
Labels: enhancement

#82 feat: add solidity lang icon
  assets/icons/solidity.png
  src/data/languages.json
Labels: enhancement

#77 feat: add grain lang icon
  assets/icons/grain.png
  src/data/languages.json
Labels: enhancement

#76 feat: folder_and_file variable
  package.json
  src/activity.ts
  src/constants.ts
  src/data.ts
Labels: enhancement

#104 feat: use controller system to manage ratelimit and connection
  README.md
  assets/icons/README.md
  assets/icons/c3.png
  package.json
  src/activity.ts
  src/config.ts
  src/constants.ts
  src/controller.ts
  src/data.ts
  src/data/README.md
  src/data/languages.json
  src/extension.ts
  src/helpers/getApplicationId.ts
  src/helpers/resolveFileIcon.ts
  yarn.lock
Labels: enhancement

#105 Add hare logo to icons
  assets/icons/README.md
  assets/icons/hare.png
Labels: enhancement

#114 Feat/config rewrite - @Depracted settings
  package.json
Labels: enhancement

#109 feat: better config file and more customization
  .husky/pre-commit
  README.md
  assets/icons/README.md
  assets/icons/idle-vscodium-insiders.png
  assets/icons/idle-vscodium.png
  package.json
  src/activity.ts
  src/config.ts
  src/constants.ts
  src/controller.ts
  src/data.ts
  src/extension.ts
  src/helpers/getApplicationId.ts
  src/helpers/getFileSize.ts
  src/helpers/isObject.ts
  src/helpers/resolveLangName.ts
  src/helpers/throttle.ts
  src/logger.ts
  tsconfig.json
  tsup.config.ts
  yarn.lock
Labels: enhancement, help wanted

#115 Add fortran logo
  assets/icons/fortran.png
  src/data/languages.json
Labels: enhancement

#126 feat: eslint and multiple stuff
  .eslintignore
  .eslintrc.cjs
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  .github/workflows/cd-vs-marketplace.yml
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  ADDING_LANGUAGE.md
  README.md
  assets/icons/README.md
  package.json
  src/activity.ts
  src/config.ts
  src/controller.ts
  src/data.ts
  src/extension.ts
  src/helpers/getFileSize.ts
  src/helpers/isObject.ts
  src/helpers/throttle.ts
  src/logger.ts
  tsconfig.json
  tsup.config.ts
  yarn.lock
Labels: documentation, enhancement

#128 Disable all {problems} text when settings is disabled
  src/activity.ts
Labels: enhancement

#132 docs: move variables to readme
  README.md
  package.json
Labels: documentation, enhancement

#129 chore: code cleanup
  .eslintrc.cjs
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  package.json
  src/activity.ts
  src/constants.ts
  src/controller.ts
  src/extension.ts
  src/helpers/getFileSize.ts
  src/helpers/resolveLangName.ts
  src/logger.ts
  yarn.lock
Labels: enhancement

#134 Advanced problem config
  README.md
  package.json
  src/activity.ts
  src/config.ts
  src/constants.ts
Labels: enhancement
